/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerConfirmRouteImport } from './routes/customer.confirm'
import { Route as CustomerResultRouteImport } from './routes/customer.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerConfirmRoute = CustomerConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerResultRoute = CustomerResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/confirm': typeof CustomerConfirmRoute
  '/customer/result': typeof CustomerResultRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer/confirm': typeof CustomerConfirmRoute
  '/customer/result': typeof CustomerResultRoute
  '/customer': typeof CustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/confirm': typeof CustomerConfirmRoute
  '/customer/result': typeof CustomerResultRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/customer' | '/customer/confirm' | '/customer/result' | '/customer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customer/confirm' | '/customer/result' | '/customer'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/customer/confirm'
    | '/customer/result'
    | '/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/confirm': {
      id: '/customer/confirm'
      path: '/confirm'
      fullPath: '/customer/confirm'
      preLoaderRoute: typeof CustomerConfirmRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/result': {
      id: '/customer/result'
      path: '/result'
      fullPath: '/customer/result'
      preLoaderRoute: typeof CustomerResultRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerConfirmRoute: typeof CustomerConfirmRoute
  CustomerResultRoute: typeof CustomerResultRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerConfirmRoute: CustomerConfirmRoute,
  CustomerResultRoute: CustomerResultRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
